version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libp2p
    versions:
    - 0.31.0-rc.2
    - 0.31.0-rc.3
    - 0.31.0-rc.6
  - dependency-name: libp2p-interfaces
    versions:
    - 0.10.0
    - 0.9.0
  - dependency-name: aegir
    versions:
    - 30.3.0
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 32.1.0
    - 32.2.0
    - 33.0.0
    - 33.1.0
  - dependency-name: it-length-prefixed
    versions:
    - 4.0.0
    - 5.0.0
    - 5.0.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: iso-random-stream
    versions:
    - 2.0.0
  - dependency-name: ipfs-repo
    versions:
    - 8.0.0
    - 9.0.0
  - dependency-name: multicodec
    versions:
    - 3.0.1
  - dependency-name: libp2p-kad-dht
    versions:
    - 0.21.0
  - dependency-name: delay
    versions:
    - 5.0.0
