on:
  push:
    branches:
      - master
      - main
      - default
  pull_request:
    branches:
      - '**'

name: Typecheck
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
